package rw.terimbere.csams.modules.report.export;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import rw.terimbere.csams.modules.report.dto.MemberContributionAggregate;
import rw.terimbere.csams.modules.report.dto.ReportSheetData;
import rw.terimbere.csams.modules.report.financial.FullFinancialReportModel;
import rw.terimbere.csams.modules.report.service.ReportTimelineValidator;

/**
 * Specialized landscape PDF for FULL_FINANCIAL statement pack (preserves OuWealth branding).
 */
public final class FullFinancialPdfWriter {

    private static final ZoneId ZONE = ReportTimelineValidator.ZONE;
    private static final DateTimeFormatter LONG_DATE =
            DateTimeFormatter.ofPattern("MMMM d, yyyy", Locale.ENGLISH);
    private static final DateTimeFormatter DATE_TIME =
            DateTimeFormatter.ofPattern("MMMM d, yyyy HH:mm").withZone(ZONE);

    private FullFinancialPdfWriter() {}

    public static byte[] write(FullFinancialReportModel model) {
        Document document = new Document(PageSize.A4.rotate(), 36, 36, 42, 42);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter writer = PdfWriter.getInstance(document, out);
            writer.setPageEvent(new FooterEvent(model.getHeader().getCooperativeName()));
            document.open();

            writeCover(document, model);
            document.newPage();
            writeExecutiveSummary(document, model);
            document.newPage();
            writeFinancialPosition(document, model);
            document.newPage();
            writeOperating(document, model);
            document.newPage();
            writeCashFlow(document, model);
            document.newPage();
            writeMemberContributions(document, model);
            document.newPage();
            writeAppendixAndNotes(document, model);

            document.close();
            return out.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to build Full Financial PDF", ex);
        } finally {
            if (document.isOpen()) {
                try {
                    document.close();
                } catch (Exception ignored) {
                    // Prefer the original exception.
                }
            }
        }
    }

    private static void writeCover(Document document, FullFinancialReportModel model) throws DocumentException {
        FullFinancialReportModel.Header h = model.getHeader();
        writeBanner(document, h.getReportTitle());

        PdfPTable meta = new PdfPTable(2);
        meta.setWidthPercentage(100);
        meta.setWidths(new float[] {1.4f, 3.6f});
        meta.setSpacingAfter(12);
        addMetaRow(meta, "Brand", h.getBrandName());
        addMetaRow(meta, "Saving Scheme", h.getCooperativeName());
        addMetaRow(meta, "Reporting Period", h.getPeriodLabel());
        addMetaRow(
                meta,
                "Financial Position",
                "Current snapshot as of " + LONG_DATE.format(h.getSnapshotAsOf()));
        addMetaRow(meta, "Generated", DATE_TIME.format(h.getGeneratedAt()));
        addMetaRow(meta, "Currency", h.getCurrency());
        if (h.getGeneratedBy() != null && !h.getGeneratedBy().isBlank()) {
            addMetaRow(meta, "Generated by", h.getGeneratedBy());
        }
        document.add(meta);

        Paragraph note = new Paragraph(
                pdfText(
                        "Period activity (Income, Cash Flow, Contributions) covers the selected reporting period. "
                                + "Financial Position is a current snapshot and is not reconstructed historically as of the period end date.",
                        ""),
                PdfReportStyle.table(9, PdfReportStyle.MUTED));
        note.setSpacingBefore(8);
        document.add(note);
    }

    private static void writeExecutiveSummary(Document document, FullFinancialReportModel model)
            throws DocumentException {
        sectionHeading(document, "Executive Summary");
        PdfPTable table = twoColTable();
        headerPair(table, "Metric", "Amount");
        for (FullFinancialReportModel.SummaryMetric m : model.getExecutiveSummary()) {
            String scope = "PERIOD".equals(m.getScope()) ? " (Selected Period)" : " (Current Snapshot)";
            linePair(table, m.getLabel() + scope, money(m.getAmount(), model.getHeader().getCurrency()), false);
        }
        document.add(table);
    }

    private static void writeFinancialPosition(Document document, FullFinancialReportModel model)
            throws DocumentException {
        FullFinancialReportModel.FinancialPosition pos = model.getCurrentPosition();
        sectionHeading(document, "Financial Position — Current Snapshot");
        Paragraph asOf = new Paragraph(
                pdfText("As of " + LONG_DATE.format(pos.getSnapshotAsOfDate()), ""),
                PdfReportStyle.table(9, PdfReportStyle.MUTED));
        asOf.setSpacingAfter(8);
        document.add(asOf);

        PdfPTable table = twoColTable();
        headerPair(table, "Measure", "Amount");
        for (FullFinancialReportModel.StatementLine line : pos.getAssetLines()) {
            boolean total = "TOTAL".equals(line.getKind());
            linePair(table, line.getLabel(), money(line.getAmount(), model.getHeader().getCurrency()), total);
        }
        document.add(table);

        mutedNote(document, pos.getIkiminaValueNote());
        mutedNote(document, pos.getLiabilitiesNote());
        mutedNote(
                document,
                "Social Fund Balance (separate): "
                        + money(pos.getSocialFundBalance(), model.getHeader().getCurrency()));
        for (String n : pos.getReconciliationNotes()) {
            mutedNote(document, n);
        }
    }

    private static void writeOperating(Document document, FullFinancialReportModel model) throws DocumentException {
        FullFinancialReportModel.OperatingStatement op = model.getOperatingStatement();
        sectionHeading(document, "Operating Income & Expenses");
        mutedNote(
                document,
                "For " + LONG_DATE.format(op.getPeriodFrom()) + " through " + LONG_DATE.format(op.getPeriodTo()));

        categoryHeading(document, "Operating Income");
        PdfPTable income = twoColTable();
        for (FullFinancialReportModel.StatementLine line : op.getIncomeLines()) {
            linePair(income, line.getLabel(), money(line.getAmount(), model.getHeader().getCurrency()), false);
        }
        linePair(
                income,
                "Total Operating Income",
                money(op.getTotalOperatingIncome(), model.getHeader().getCurrency()),
                true);
        document.add(income);

        categoryHeading(document, "Operating Expenses");
        PdfPTable expense = twoColTable();
        for (FullFinancialReportModel.StatementLine line : op.getExpenseLines()) {
            linePair(expense, line.getLabel(), money(line.getAmount(), model.getHeader().getCurrency()), false);
        }
        linePair(
                expense,
                "Total Operating Expenses",
                money(op.getTotalOperatingExpenses(), model.getHeader().getCurrency()),
                true);
        document.add(expense);

        PdfPTable net = twoColTable();
        net.setSpacingBefore(10);
        linePair(
                net,
                op.getNetResultLabel(),
                money(op.getNetOperatingResult(), model.getHeader().getCurrency()),
                true);
        document.add(net);
        mutedNote(document, "Member contributions and share purchases are not classified as operating income.");
    }

    private static void writeCashFlow(Document document, FullFinancialReportModel model) throws DocumentException {
        FullFinancialReportModel.CashFlowStatement cf = model.getCashFlow();
        sectionHeading(document, "Cash Flow Statement");
        mutedNote(
                document,
                "For " + LONG_DATE.format(cf.getPeriodFrom()) + " through " + LONG_DATE.format(cf.getPeriodTo())
                        + " (approved main-fund ledger entries)");

        categoryHeading(document, "Cash Inflows");
        PdfPTable in = twoColTable();
        for (FullFinancialReportModel.StatementLine line : cf.getInflowLines()) {
            linePair(in, line.getLabel(), money(line.getAmount(), model.getHeader().getCurrency()), false);
        }
        linePair(in, "Total Cash Inflows", money(cf.getTotalInflows(), model.getHeader().getCurrency()), true);
        document.add(in);

        categoryHeading(document, "Cash Outflows");
        PdfPTable out = twoColTable();
        for (FullFinancialReportModel.StatementLine line : cf.getOutflowLines()) {
            linePair(out, line.getLabel(), money(line.getAmount(), model.getHeader().getCurrency()), false);
        }
        linePair(out, "Total Cash Outflows", money(cf.getTotalOutflows(), model.getHeader().getCurrency()), true);
        document.add(out);

        categoryHeading(document, "Ledger Balance Bridge");
        PdfPTable bridge = twoColTable();
        linePair(
                bridge,
                "Opening Ledger Balance",
                money(cf.getOpeningLedgerBalance(), model.getHeader().getCurrency()),
                false);
        linePair(bridge, "Net Cash Movement", money(cf.getNetCashMovement(), model.getHeader().getCurrency()), false);
        linePair(
                bridge,
                "Closing Ledger Balance",
                money(cf.getClosingLedgerBalance(), model.getHeader().getCurrency()),
                true);
        document.add(bridge);

        if (!cf.isReconciliationHolds()) {
            mutedNote(
                    document,
                    "Note: Opening + Net Cash Movement did not equal Closing Ledger Balance for this period. "
                            + "Review adjustments/reversals and excluded Social Fund entries.");
        }
        mutedNote(document, cf.getSocialFundNote());
        mutedNote(
                document,
                "Social Fund period net: " + money(cf.getSocialFundPeriodNet(), model.getHeader().getCurrency()));
    }

    private static void writeMemberContributions(Document document, FullFinancialReportModel model)
            throws DocumentException {
        FullFinancialReportModel.MemberContributionSection section = model.getMemberContributions();
        sectionHeading(document, section.getSheetTitle());

        List<String> headers = section.getHeaders();
        PdfPTable table = new PdfPTable(headers.size());
        table.setWidthPercentage(100);
        table.setHeaderRows(1);
        table.setSpacingAfter(10);
        Font headerFont = PdfReportStyle.tableBold(8, Color.WHITE);
        Font cellFont = PdfReportStyle.table(8, Color.BLACK);
        Font totalFont = PdfReportStyle.tableBold(8, Color.BLACK);
        for (String h : headers) {
            table.addCell(headerCell(h, headerFont));
        }
        for (MemberContributionAggregate row : section.getRows()) {
            if (section.isSingleMonth()) {
                table.addCell(bodyCell(pdfText(row.getMemberName(), ""), cellFont, false));
                table.addCell(bodyCell(formatDecimal(row.getExpectedAmount()), cellFont, true));
                table.addCell(bodyCell(formatDecimal(row.getPaidAmount()), cellFont, true));
                table.addCell(bodyCell(formatDecimal(row.getRemainingAmount()), cellFont, true));
                table.addCell(bodyCell(pdfText(row.getStatus(), ""), cellFont, false));
            } else {
                table.addCell(bodyCell(pdfText(row.getMemberName(), ""), cellFont, false));
                table.addCell(bodyCell(String.valueOf(row.getPeriodsCounted()), cellFont, true));
                table.addCell(bodyCell(formatDecimal(row.getExpectedAmount()), cellFont, true));
                table.addCell(bodyCell(formatDecimal(row.getPaidAmount()), cellFont, true));
                table.addCell(bodyCell(formatDecimal(row.getRemainingAmount()), cellFont, true));
                table.addCell(bodyCell(formatDecimal(row.getOverpaidAmount()), cellFont, true));
            }
        }
        // totals
        if (section.isSingleMonth()) {
            table.addCell(bodyCell("TOTAL", totalFont, false));
            table.addCell(bodyCell(formatDecimal(section.getTotalExpected()), totalFont, true));
            table.addCell(bodyCell(formatDecimal(section.getTotalPaid()), totalFont, true));
            table.addCell(bodyCell(formatDecimal(section.getTotalRemaining()), totalFont, true));
            table.addCell(bodyCell("", totalFont, false));
        } else {
            table.addCell(bodyCell("TOTAL", totalFont, false));
            table.addCell(bodyCell(String.valueOf(section.getTotalPeriodsCounted()), totalFont, true));
            table.addCell(bodyCell(formatDecimal(section.getTotalExpected()), totalFont, true));
            table.addCell(bodyCell(formatDecimal(section.getTotalPaid()), totalFont, true));
            table.addCell(bodyCell(formatDecimal(section.getTotalRemaining()), totalFont, true));
            table.addCell(bodyCell(formatDecimal(section.getTotalOverpaid()), totalFont, true));
        }
        document.add(table);
    }

    private static void writeAppendixAndNotes(Document document, FullFinancialReportModel model)
            throws DocumentException {
        sectionHeading(document, "Supporting Schedules");
        for (ReportSheetData sheet : model.getSupportingSchedules()) {
            categoryHeading(document, sheet.getSheetName());
            document.add(buildGenericTable(sheet));
        }
        sectionHeading(document, "Notes");
        for (String note : model.getNotes()) {
            mutedNote(document, "• " + note);
        }
    }

    private static PdfPTable buildGenericTable(ReportSheetData data) throws DocumentException {
        List<String> headers = data.getHeaders() == null ? List.of() : data.getHeaders();
        int columns = Math.max(1, headers.size());
        PdfPTable table = new PdfPTable(columns);
        table.setWidthPercentage(100);
        table.setHeaderRows(1);
        table.setSpacingAfter(12);
        Font headerFont = PdfReportStyle.tableBold(8, Color.WHITE);
        Font cellFont = PdfReportStyle.table(8, Color.BLACK);
        for (String h : headers) {
            table.addCell(headerCell(h, headerFont));
        }
        if (data.getRows() != null) {
            boolean zebra = false;
            for (List<Object> row : data.getRows()) {
                for (int i = 0; i < columns; i++) {
                    Object value = row != null && i < row.size() ? row.get(i) : null;
                    table.addCell(bodyCell(formatCell(value), cellFont, value instanceof Number));
                }
                zebra = !zebra;
            }
        }
        return table;
    }

    private static void writeBanner(Document document, String title) throws DocumentException {
        Image logo = PdfReportStyle.logo();
        PdfPTable banner = new PdfPTable(logo == null ? 1 : 2);
        banner.setWidthPercentage(100);
        if (logo != null) {
            banner.setWidths(new float[] {2.15f, 7.85f});
            PdfPCell logoCell = new PdfPCell(logo, false);
            logoCell.setBorder(Rectangle.NO_BORDER);
            logoCell.setPaddingRight(10);
            logoCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            banner.addCell(logoCell);
        }
        PdfPCell titleCell = new PdfPCell(new Phrase(
                pdfText(title, "Report").toUpperCase(Locale.ROOT),
                PdfReportStyle.heading(16, PdfReportStyle.BRAND_BLUE)));
        titleCell.setBorder(Rectangle.NO_BORDER);
        titleCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        banner.addCell(titleCell);
        document.add(banner);

        PdfPTable accent = new PdfPTable(1);
        accent.setWidthPercentage(100);
        accent.setSpacingAfter(10);
        PdfPCell bar = new PdfPCell(new Phrase(" "));
        bar.setBackgroundColor(PdfReportStyle.BRAND_ORANGE);
        bar.setBorder(Rectangle.NO_BORDER);
        bar.setFixedHeight(4f);
        accent.addCell(bar);
        document.add(accent);
    }

    private static void sectionHeading(Document document, String text) throws DocumentException {
        Paragraph p = new Paragraph(pdfText(text, "Section"), PdfReportStyle.heading(12, PdfReportStyle.BRAND_BLUE));
        p.setSpacingBefore(4);
        p.setSpacingAfter(8);
        document.add(p);
    }

    private static void categoryHeading(Document document, String text) throws DocumentException {
        Paragraph p = new Paragraph(pdfText(text, ""), PdfReportStyle.tableBold(10, PdfReportStyle.BRAND_BLUE));
        p.setSpacingBefore(8);
        p.setSpacingAfter(4);
        document.add(p);
    }

    private static void mutedNote(Document document, String text) throws DocumentException {
        if (text == null || text.isBlank()) {
            return;
        }
        Paragraph p = new Paragraph(pdfText(text, ""), PdfReportStyle.table(8, PdfReportStyle.MUTED));
        p.setSpacingBefore(3);
        p.setSpacingAfter(3);
        document.add(p);
    }

    private static PdfPTable twoColTable() throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setWidths(new float[] {3.2f, 1.4f});
        table.setSpacingAfter(6);
        return table;
    }

    private static void headerPair(PdfPTable table, String left, String right) {
        Font font = PdfReportStyle.tableBold(8, Color.WHITE);
        table.addCell(headerCell(left, font));
        table.addCell(headerCell(right, font));
    }

    private static void linePair(PdfPTable table, String label, String amount, boolean emphasize) {
        Font font = emphasize
                ? PdfReportStyle.tableBold(9, Color.BLACK)
                : PdfReportStyle.table(8, Color.BLACK);
        PdfPCell labelCell = new PdfPCell(new Phrase(pdfText(label, ""), font));
        labelCell.setBorderColor(PdfReportStyle.GRID);
        labelCell.setPadding(5);
        if (emphasize) {
            labelCell.setBackgroundColor(PdfReportStyle.TOTALS_BG);
            labelCell.setBorderColor(PdfReportStyle.BRAND_ORANGE);
        }
        table.addCell(labelCell);

        PdfPCell amountCell = new PdfPCell(new Phrase(pdfText(amount, ""), font));
        amountCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        amountCell.setBorderColor(PdfReportStyle.GRID);
        amountCell.setPadding(5);
        if (emphasize) {
            amountCell.setBackgroundColor(PdfReportStyle.TOTALS_BG);
            amountCell.setBorderColor(PdfReportStyle.BRAND_ORANGE);
        }
        table.addCell(amountCell);
    }

    private static void addMetaRow(PdfPTable table, String label, String value) {
        Font labelFont = PdfReportStyle.tableBold(8, PdfReportStyle.MUTED);
        Font valueFont = PdfReportStyle.table(9, Color.BLACK);
        PdfPCell l = new PdfPCell(new Phrase(label.toUpperCase(Locale.ROOT), labelFont));
        l.setBackgroundColor(PdfReportStyle.META_BG);
        l.setBorderColor(PdfReportStyle.GRID);
        l.setPadding(6);
        table.addCell(l);
        PdfPCell v = new PdfPCell(new Phrase(pdfText(value, ""), valueFont));
        v.setBackgroundColor(PdfReportStyle.META_BG);
        v.setBorderColor(PdfReportStyle.GRID);
        v.setPadding(6);
        table.addCell(v);
    }

    private static PdfPCell headerCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(pdfText(text, ""), font));
        cell.setBackgroundColor(PdfReportStyle.BRAND_BLUE);
        cell.setBorderColor(PdfReportStyle.BRAND_BLUE_DARK);
        cell.setPadding(6);
        return cell;
    }

    private static PdfPCell bodyCell(String text, Font font, boolean numeric) {
        PdfPCell cell = new PdfPCell(new Phrase(pdfText(text, ""), font));
        cell.setPadding(5);
        cell.setBorderColor(PdfReportStyle.GRID);
        cell.setHorizontalAlignment(numeric ? Element.ALIGN_RIGHT : Element.ALIGN_LEFT);
        return cell;
    }

    private static String money(BigDecimal amount, String currency) {
        String code = currency == null || currency.isBlank() ? "RWF" : currency;
        BigDecimal value = amount == null ? BigDecimal.ZERO : amount;
        if (value.signum() < 0) {
            return "(" + code + " " + formatDecimal(value.abs()) + ")";
        }
        return code + " " + formatDecimal(value);
    }

    private static String formatDecimal(BigDecimal value) {
        if (value == null) {
            return "0";
        }
        DecimalFormatSymbols symbols = DecimalFormatSymbols.getInstance(Locale.US);
        DecimalFormat format = new DecimalFormat("#,##0.00", symbols);
        return format.format(value);
    }

    private static String formatCell(Object value) {
        if (value == null) {
            return "";
        }
        if (value instanceof BigDecimal bd) {
            return formatDecimal(bd);
        }
        return pdfText(String.valueOf(value), "");
    }

    private static String pdfText(String text, String blankFallback) {
        if (text == null || text.isBlank()) {
            return blankFallback == null ? "" : blankFallback;
        }
        String normalized = text
                .replace('\u2018', '\'')
                .replace('\u2019', '\'')
                .replace('\u201C', '"')
                .replace('\u201D', '"')
                .replace('\u2013', '-')
                .replace('\u2014', '-')
                .replace('\u00A0', ' ')
                .replace('–', '-');
        if (PdfReportStyle.hasCandara()) {
            return normalized.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ');
        }
        StringBuilder safe = new StringBuilder(normalized.length());
        for (int i = 0; i < normalized.length(); i++) {
            char ch = normalized.charAt(i);
            if (ch == '\n' || ch == '\r' || ch == '\t') {
                safe.append(' ');
            } else if (ch == ' ' || ch == '\'' || ch == '"' || (ch >= 0x20 && ch <= 0x7E) || (ch >= 0xA0 && ch <= 0xFF)) {
                safe.append(ch);
            } else {
                safe.append('?');
            }
        }
        return safe.toString();
    }

    private static final class FooterEvent extends PdfPageEventHelper {
        private final String line;

        private FooterEvent(String cooperativeName) {
            String coop = pdfText(cooperativeName == null ? "" : cooperativeName, "");
            this.line = coop.isBlank() ? "Confidential" : coop + "  ·  Confidential";
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            try {
                PdfPTable footer = new PdfPTable(1);
                footer.setTotalWidth(document.right() - document.left());
                footer.addCell(new Phrase(line, PdfReportStyle.table(7, PdfReportStyle.MUTED)));
                footer.writeSelectedRows(0, -1, document.left(), document.bottom() - 10, writer.getDirectContent());
            } catch (Exception ignored) {
                // Footer must not fail the report.
            }
        }
    }
}
